export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const MODIFY_START = "MODIFY_START";
export const MODIFY_SUCCESS = "MODIFY_SUCCESS";
export const MODIFY_FAILURE = "MODIFY_FAILURE";
